version: '3.10'
services:
  app:
    container_name: lanchonete-app-pagamento
    image: lanchonete-app:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    container_name: mongo-lanchonete-pagamento
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "mongodb://admin:password@localhost:27017/admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbit:
    container_name: rabbitmq-lanchonete-pagamento
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=adm_payment
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo-data:
