apiVersion: v1
kind: ResourceQuota
metadata:
  name: payment-quota
  namespace: payment-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"